describe('template spec', () => {
  it('passes', () => {
    cy.visit('http://localhost:3000')
    cy.contains('Hjem').click()
    cy.wait(200)
    cy.get(':nth-child(1) > :nth-child(1) > a > .ant-card > .ant-card-cover > img').click()
    cy.wait(200)
    cy.contains('Arkiv').click()
    cy.wait(200)
    cy.get('#search-button').type('Anabole steroider')
    cy.wait(200)
    cy.contains('Melsom Støle').click()
    cy.wait(200)
    cy.contains('Om oss').click()
    cy.wait(200)
    cy.contains('Fredrik Sjøberg')
    cy.wait(200)
    cy.contains('Kontakt oss').click()
  })
})