describe('template spec', () => {
  it('passes', () => {
    cy.visit('http://localhost:3000')
    cy.wait(800)
    cy.contains('Hjem').click()
    cy.wait(800)
    cy.get('.ant-card').first().click()
    cy.wait(800)
    cy.contains('Arkiv').click()
    cy.wait(800)
    cy.get('#search-button').type('Anabole steroider')
    cy.wait(800)
    cy.contains('Melsom Støle').click()
    cy.wait(800)
    cy.contains('Om oss').click()
    cy.wait(800)
    cy.contains('Fredrik Sjøberg')
    cy.wait(800)
    cy.contains('Kontakt oss').click()
  })
})