describe('template spec', () => {
  it('passes', () => {
    cy.visit('http://localhost:3000')
    cy.wait(800)
    cy.contains('Hjem').click()
    cy.wait(800)
    cy.get('.ant-card').first().click()
    cy.wait(800)
    cy.contains('Arkiv').click()
    cy.wait(800)
    cy.get('#search-button').should('be.visible')
    cy.wait(500)
    cy.get('.ant-card').should('have.length.at.least', 1)
    cy.wait(800)
    cy.contains('Om oss').click()
    cy.wait(800)
    cy.contains('Fysi Kollektivet').should('be.visible')
    cy.get('.ant-card').should('have.length.at.least', 1)
    cy.wait(800)
    cy.contains('Kontakt oss').click()
  })
})