name: End-to-end tests
on: [push]
jobs:
  cypress-run: 
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout 🚚
        uses: actions/checkout@v3
      - name: Cypress run 🧪
        uses: cypress-io/github-action@v5
        with:
          start: npm run dev
          wait-on: "http://localhost:3000"
          wait-on-timeout: 120
          command: npx cypress run
